%% Example of sequence diagram
sequenceDiagram
  participant Bugs
  participant Feature
  participant Updates
  participant Staging
  participant Releases
  participant Master

  Note over Bugs, Staging: Treat bugs like features and roll them into the following release.
  Bugs ->>+ Staging: Open a pull request
  Note left of Staging: Review the changes locally during a pairing session to ensure bug is fixed before merging.
  Staging -->>- Bugs: Delete bug branch
  Note over Bugs, Staging: Deploys to staging URL on merge to Staging from Bugs.

  Feature ->>+ Staging: Open a pull request
  Note left of Staging: Review the changes locally before merging.
  Staging -->>- Feature: Delete feature branch
  Note over Feature, Staging: Deploys to staging URL on merge to Staging from Feature.

  loop Updates to Feature
    Updates ->>+ Feature: Open a pull request
    Note right of Feature: Review the changes locally before merging.
    Note right of Updates: If large changes need to occur on a feature, don't just add commits to the original branch. Open an update feature branch and merge it into the feature. This way updates and or features don't balloon to large commit sizes without verifying updates in between.
    Feature -->>- Updates: Delete update branch
  end

  Note right of Releases: Follow semantic versioning when deploying to Releases. Any breaking changes should bump the major and minor versions respectively.

  Staging ->> Releases: Open a pull request
  Note over Staging, Releases: Deploys to releases URL on merge to Releases from Staging.

  Releases ->> Master: Open a pull request
  Note over Releases, Master: Deploys to production URL on merge to Master from Releases.

  Master -->> Staging: Open a pull request
  Note over Master, Staging: Sync back changes for version numbers or fixes, if necessary.
